channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1.1
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - numpy==2.3.0
  - pandas==2.3.0
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.15.3
name: mlflow-env
